export type Book = {
  id: string;
  en: string;
  ru: string;
  es: string;
  chapters: number;
};

export const BOOKS: Book[] = [
  { id: "genesis",        en: "Genesis",          ru: "Бытие",            es: "Génesis",       chapters: 50 },
  { id: "exodus",         en: "Exodus",           ru: "Исход",            es: "Éxodo",         chapters: 40 },
  { id: "leviticus",      en: "Leviticus",        ru: "Левит",            es: "Levítico",      chapters: 27 },
  { id: "numbers",        en: "Numbers",          ru: "Числа",            es: "Números",       chapters: 36 },
  { id: "deuteronomy",    en: "Deuteronomy",      ru: "Второзаконие",     es: "Deuteronomio",  chapters: 34 },
  { id: "joshua",         en: "Joshua",           ru: "Иисус Навин",      es: "Josué",         chapters: 24 },
  { id: "judges",         en: "Judges",           ru: "Судьи",            es: "Jueces",        chapters: 21 },
  { id: "ruth",           en: "Ruth",             ru: "Руфь",             es: "Rut",           chapters: 4  },
  { id: "1samuel",        en: "1 Samuel",         ru: "1 Царств",         es: "1 Samuel",      chapters: 31 },
  { id: "2samuel",        en: "2 Samuel",         ru: "2 Царств",         es: "2 Samuel",      chapters: 24 },
  { id: "1kings",         en: "1 Kings",          ru: "3 Царств",         es: "1 Reyes",       chapters: 22 },
  { id: "2kings",         en: "2 Kings",          ru: "4 Царств",         es: "2 Reyes",       chapters: 25 },
  { id: "1chronicles",    en: "1 Chronicles",     ru: "1 Паралипоменон",  es: "1 Crónicas",    chapters: 29 },
  { id: "2chronicles",    en: "2 Chronicles",     ru: "2 Паралипоменон",  es: "2 Crónicas",    chapters: 36 },
  { id: "ezra",           en: "Ezra",             ru: "Ездра",            es: "Esdras",        chapters: 10 },
  { id: "nehemiah",       en: "Nehemiah",         ru: "Неемия",           es: "Nehemías",      chapters: 13 },
  { id: "esther",         en: "Esther",           ru: "Есфирь",           es: "Ester",         chapters: 10 },
  { id: "job",            en: "Job",              ru: "Иов",              es: "Job",           chapters: 42 },
  { id: "psalms",         en: "Psalms",           ru: "Псалтирь",         es: "Salmos",        chapters: 150 },
  { id: "proverbs",       en: "Proverbs",         ru: "Притчи",           es: "Proverbios",    chapters: 31 },
  { id: "ecclesiastes",   en: "Ecclesiastes",     ru: "Екклесиаст",       es: "Eclesiastés",   chapters: 12 },
  { id: "song",           en: "Song of Solomon",  ru: "Песнь Песней",     es: "Cantares",      chapters: 8  },
  { id: "isaiah",         en: "Isaiah",           ru: "Исаия",            es: "Isaías",        chapters: 66 },
  { id: "jeremiah",       en: "Jeremiah",         ru: "Иеремия",          es: "Jeremías",      chapters: 52 },
  { id: "lamentations",   en: "Lamentations",     ru: "Плач Иеремии",     es: "Lamentaciones", chapters: 5  },
  { id: "ezekiel",        en: "Ezekiel",          ru: "Иезекииль",        es: "Ezequiel",      chapters: 48 },
  { id: "daniel",         en: "Daniel",           ru: "Даниил",           es: "Daniel",        chapters: 12 },
  { id: "hosea",          en: "Hosea",            ru: "Осия",             es: "Oseas",         chapters: 14 },
  { id: "joel",           en: "Joel",             ru: "Иоиль",            es: "Joel",          chapters: 3  },
  { id: "amos",           en: "Amos",             ru: "Амос",             es: "Amós",          chapters: 9  },
  { id: "obadiah",        en: "Obadiah",          ru: "Авдий",            es: "Abdías",        chapters: 1  },
  { id: "jonah",          en: "Jonah",            ru: "Иона",             es: "Jonás",         chapters: 4  },
  { id: "micah",          en: "Micah",            ru: "Михей",            es: "Miqueas",       chapters: 7  },
  { id: "nahum",          en: "Nahum",            ru: "Наум",             es: "Nahúm",         chapters: 3  },
  { id: "habakkuk",       en: "Habakkuk",         ru: "Аввакум",          es: "Habacuc",       chapters: 3  },
  { id: "zephaniah",      en: "Zephaniah",        ru: "Софония",          es: "Sofonías",      chapters: 3  },
  { id: "haggai",         en: "Haggai",           ru: "Аггей",            es: "Hageo",         chapters: 2  },
  { id: "zechariah",      en: "Zechariah",        ru: "Захария",          es: "Zacarías",      chapters: 14 },
  { id: "malachi",        en: "Malachi",          ru: "Малахия",          es: "Malaquías",     chapters: 4  },
  { id: "matthew",        en: "Matthew",          ru: "Матфея",           es: "Mateo",         chapters: 28 },
  { id: "mark",           en: "Mark",             ru: "Марка",            es: "Marcos",        chapters: 16 },
  { id: "luke",           en: "Luke",             ru: "Луки",             es: "Lucas",         chapters: 24 },
  { id: "john",           en: "John",             ru: "Иоанна",           es: "Juan",          chapters: 21 },
  { id: "acts",           en: "Acts",             ru: "Деяния",           es: "Hechos",        chapters: 28 },
  { id: "romans",         en: "Romans",           ru: "Римлянам",         es: "Romanos",       chapters: 16 },
  { id: "1corinthians",   en: "1 Corinthians",    ru: "1 Коринфянам",     es: "1 Corintios",   chapters: 16 },
  { id: "2corinthians",   en: "2 Corinthians",    ru: "2 Коринфянам",     es: "2 Corintios",   chapters: 13 },
  { id: "galatians",      en: "Galatians",        ru: "Галатам",          es: "Gálatas",       chapters: 6  },
  { id: "ephesians",      en: "Ephesians",        ru: "Ефесянам",         es: "Efesios",       chapters: 6  },
  { id: "philippians",    en: "Philippians",      ru: "Филиппийцам",      es: "Filipenses",    chapters: 4  },
  { id: "colossians",     en: "Colossians",       ru: "Колоссянам",       es: "Colosenses",    chapters: 4  },
  { id: "1thessalonians", en: "1 Thessalonians",  ru: "1 Фессалоникийцам", es: "1 Tesalonicenses", chapters: 5 },
  { id: "2thessalonians", en: "2 Thessalonians",  ru: "2 Фессалоникийцам", es: "2 Tesalonicenses", chapters: 3 },
  { id: "1timothy",       en: "1 Timothy",        ru: "1 Тимофею",        es: "1 Timoteo",     chapters: 6  },
  { id: "2timothy",       en: "2 Timothy",        ru: "2 Тимофею",        es: "2 Timoteo",     chapters: 4  },
  { id: "titus",          en: "Titus",            ru: "Титу",             es: "Tito",          chapters: 3  },
  { id: "philemon",       en: "Philemon",         ru: "Филимону",         es: "Filemón",       chapters: 1  },
  { id: "hebrews",        en: "Hebrews",          ru: "Евреям",           es: "Hebreos",       chapters: 13 },
  { id: "james",          en: "James",            ru: "Иакова",           es: "Santiago",      chapters: 5  },
  { id: "1peter",         en: "1 Peter",          ru: "1 Петра",          es: "1 Pedro",       chapters: 5  },
  { id: "2peter",         en: "2 Peter",          ru: "2 Петра",          es: "2 Pedro",       chapters: 3  },
  { id: "1john",          en: "1 John",           ru: "1 Иоанна",         es: "1 Juan",        chapters: 5  },
  { id: "2john",          en: "2 John",           ru: "2 Иоанна",         es: "2 Juan",        chapters: 1  },
  { id: "3john",          en: "3 John",           ru: "3 Иоанна",         es: "3 Juan",        chapters: 1  },
  { id: "jude",           en: "Jude",             ru: "Иуды",             es: "Judas",         chapters: 1  },
  { id: "revelation",     en: "Revelation",       ru: "Откровение",       es: "Apocalipsis",   chapters: 22 },
];
