import { runAI } from "../ai/runAI";
import type { Provider } from "../ai/providers";
import type { Lang } from "../i18n/dictionary";

export type VerseResult = { reference: string; text: string };
export type ChapterResult = { reference: string; text: string };

const TRANSLATION_LABEL: Record<Lang, string> = {
  en: "English Standard Version (ESV)",
  ru: "Russian Synodal translation (Синодальный перевод)",
  es: "Reina-Valera 1960",
};

/**
 * Returns the biblical text for a verse reference.
 *
 * MVP: text is generated by the selected AI provider.
 * This module is intentionally isolated so it can be swapped later for
 * a real Bible API or a static JSON source without touching the rest
 * of the app.
 */
export async function getVerseText(
  reference: string,
  lang: Lang,
  provider: Provider,
): Promise<VerseResult> {
  const translation = TRANSLATION_LABEL[lang];

  const prompt =
    `Return the exact biblical text of "${reference}" from the ${translation}. ` +
    `The verse text content MUST be in the language of that translation. ` +
    `JSON key names must ALWAYS be in English — do not translate key names. ` +
    `Output JSON only, with this exact shape: {"reference": "...", "text": "..."}. ` +
    `No commentary. No markdown. No extra keys. No prose around the JSON.`;

  const raw = await runAI(provider, prompt, lang, true);
  const parsed = extractVerseJson(raw);

  if (parsed && typeof parsed.text === "string" && parsed.text.trim().length > 0) {
    return {
      reference:
        typeof parsed.reference === "string" && parsed.reference.trim()
          ? parsed.reference.trim()
          : reference,
      text: parsed.text.trim(),
    };
  }

  const trimmed = raw.trim();

  if (trimmed.startsWith("{") || trimmed.startsWith("[")) {
    throw new Error(
      `Could not extract verse text from AI response. Raw: ${trimmed.slice(0, 120)}`,
    );
  }

  return { reference, text: trimmed };
}

/**
 * Returns the whole biblical chapter for a verse reference.
 *
 * MVP: chapter text is generated by the selected AI provider, same as getVerseText.
 * Later this should be replaced with a real Bible JSON/API source.
 *
 * Example:
 * input: "Иоанна 17:3"
 * output reference: "Иоанна 17"
 * output text:
 * 1. ...
 * 2. ...
 * 3. ...
 */
export async function getChapterText(
  reference: string,
  lang: Lang,
  provider: Provider,
): Promise<ChapterResult> {
  const translation = TRANSLATION_LABEL[lang];
  const chapterReference = getChapterReference(reference);

  const prompt =
    `Return the full biblical chapter that contains "${reference}" from the ${translation}. ` +
    `Return the chapter as numbered verses. ` +
    `The chapter text content MUST be in the language of that translation. ` +
    `Do NOT include commentary, headings, footnotes, introductions, summaries, or explanations. ` +
    `JSON key names must ALWAYS be in English — do not translate key names. ` +
    `Output JSON only, with this exact shape: ` +
    `{"reference": "${chapterReference}", "text": "1. ...\\n2. ...\\n3. ..."}. ` +
    `No markdown. No prose around the JSON.`;

  const raw = await runAI(provider, prompt, lang, true);
  const parsed = extractVerseJson(raw);

  if (parsed && typeof parsed.text === "string" && parsed.text.trim().length > 0) {
    return {
      reference:
        typeof parsed.reference === "string" && parsed.reference.trim()
          ? parsed.reference.trim()
          : chapterReference,
      text: normalizeChapterText(parsed.text),
    };
  }

  const trimmed = raw.trim();

  if (trimmed.startsWith("{") || trimmed.startsWith("[")) {
    throw new Error(
      `Could not extract chapter text from AI response. Raw: ${trimmed.slice(0, 120)}`,
    );
  }

  return {
    reference: chapterReference,
    text: normalizeChapterText(trimmed),
  };
}

function getChapterReference(reference: string): string {
  const trimmed = reference.trim();

  const colonIndex = trimmed.lastIndexOf(":");

  if (colonIndex === -1) {
    return trimmed;
  }

  return trimmed.slice(0, colonIndex).trim();
}

function normalizeChapterText(text: string): string {
  return text
    .replace(/\r\n/g, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

function extractVerseJson(s: string): { reference?: string; text?: string } | null {
  const cleaned = s
    .replace(/^```(?:json)?\s*/im, "")
    .replace(/\s*```\s*$/m, "")
    .trim();

  let obj: Record<string, unknown> | null = null;

  try {
    const val = JSON.parse(cleaned);
    if (val && typeof val === "object" && !Array.isArray(val)) {
      obj = val as Record<string, unknown>;
    }
  } catch {
    const m = cleaned.match(/\{[\s\S]*\}/);

    if (m) {
      try {
        const val = JSON.parse(m[0]);
        if (val && typeof val === "object") {
          obj = val as Record<string, unknown>;
        }
      } catch {
        // ignore
      }
    }
  }

  if (!obj) return null;

  const text =
    (typeof obj.text === "string" ? obj.text : null) ??
    (typeof obj["текст"] === "string" ? obj["текст"] : null) ??
    (typeof obj.verseText === "string" ? obj.verseText : null) ??
    (typeof obj.verse === "string" ? obj.verse : null) ??
    (typeof obj.content === "string" ? obj.content : null) ??
    Object.values(obj)
      .filter((v): v is string => typeof v === "string" && v.length > 20)
      .sort((a, b) => b.length - a.length)[0] ??
    null;

  const reference =
    (typeof obj.reference === "string" ? obj.reference : null) ??
    (typeof obj["ссылка"] === "string" ? obj["ссылка"] : null) ??
    (typeof obj.ref === "string" ? obj.ref : null) ??
    null;

  return {
    text: text ?? undefined,
    reference: reference ?? undefined,
  };
}
