import { runAI } from "../ai/runAI";
import type { Provider } from "../ai/providers";
import type { Lang } from "../i18n/dictionary";

export type VerseResult = { reference: string; text: string };

const TRANSLATION_LABEL: Record<Lang, string> = {
  en: "English Standard Version (ESV)",
  ru: "Russian Synodal translation (Синодальный перевод)",
  es: "Reina-Valera 1960",
};

/**
 * Returns the biblical text for a verse reference.
 *
 * MVP: text is generated by the selected AI provider.
 * This module is intentionally isolated so it can be swapped later for
 * a real Bible API or a static JSON source without touching the rest
 * of the app.
 */
export async function getVerseText(
  reference: string,
  lang: Lang,
  provider: Provider,
): Promise<VerseResult> {
  const translation = TRANSLATION_LABEL[lang];
  const prompt =
    `Return the exact biblical text of "${reference}" from the ${translation}. ` +
    `The verse text MUST be in the language of that translation. ` +
    `Output JSON only, with this exact shape: {"reference": string, "text": string}. ` +
    `No commentary. No markdown. No extra keys. No prose around the JSON.`;

  const raw = await runAI(provider, prompt, lang);
  const parsed = extractJson(raw);
  if (parsed && typeof parsed.text === "string" && parsed.text.trim().length > 0) {
    return {
      reference: typeof parsed.reference === "string" && parsed.reference.trim()
        ? parsed.reference.trim()
        : reference,
      text: parsed.text.trim(),
    };
  }
  // Fallback: treat the raw response as the verse text.
  return { reference, text: raw.trim() };
}

function extractJson(s: string): { reference?: unknown; text?: unknown } | null {
  const match = s.match(/\{[\s\S]*\}/);
  if (!match) return null;
  try {
    return JSON.parse(match[0]);
  } catch {
    return null;
  }
}
